---
abstract: 'Perl extension for using Futexes'
author:
  - 'Nick Townsend <nick.townsend@mac.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Linux-Futex
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  repository: https://github.com/townsen/perl-Linux-Futex
version: 0.6
